### ISSUE TITLE
DPs from 3rd party libraries

### ISSUE THREAD

**Issue by emanuelcostea** [Tensor-Reloaded/FII-Muzical#17]

**Comment by ArvinteRazvan** [comment]
Link to the document stored in git: https://github.com/Tensor-Reloaded/FII-Muzical/blob/master/Design%20patterns%20in%203rd%20party%20libraries.pdf

Link to the google docs that is editable: https://docs.google.com/document/d/1Az5hYRYXuS--rBDHBDzeS8mkQJWnf0JzMII8S44I5PU/edit#
