### ISSUE TITLE
Dataset investigation

### ISSUE THREAD

**Issue by simi2525** [Tensor-Reloaded/FII-Muzical#5]
Search and investigate potential datasets to use for training the models. Ideally a large dataset which contains separated tracks for vocals and instrumental and also the lyrics of the song and perhaps music genre classifications. 

If such a dataset can't be found, we should investigate how we can collect such data from YouTube/Spotify and aggregate it other existing sources.

**Comment by emanuelcostea** [comment]
Wrote a few findings [on the wiki](https://github.com/Tensor-Reloaded/FII-Muzical/wiki/State-of-the-art#datasets), still in discussion for what dataset we choose.
